@startuml left to right direction

actor Student
actor Administrator

rectangle "Smart Campus Study Room Booking System" {

  usecase "View Available\nStudy Rooms" as UC1
  usecase "Book Available\nStudy Room" as UC2
  usecase "Cancel Booking" as UC3
  usecase "Block or Unblock\nStudy Room" as UC4
  usecase "Review Study Room\nUsage" as UC5
  usecase "Receive\nConfirmation" as UC6
}

Student --> UC1
Student --> UC2
Student --> UC3
Student --> UC6

Administrator --> UC4
Administrator --> UC5

@enduml